### ISSUE TITLE
wiki -> Benchmarking-guidelines -> Reporting requirements -> Reference Links defective 

### ISSUE THREAD

**Issue by NicoMittenzwey** [g-koutsou/cy-tera#1]
The links to the  nucleons_sx51sy63sz46st003_gN90a0p2_aN50a0p5.h5 and     mesons_sx51sy63sz46st003_gN90a0p2_aN50a0p5.h5 reference files link to "https:///".

**Comment by g-koutsou** [comment]
Apologies for the omission. Should now be fixed in commit `d16c7f635d116331bfba0ee745c8d5a1ee43678f`. Please confirm.

**Comment by NicoMittenzwey** [comment]
Yes, links are fine now. Thank you very much.
